name: bootloader
on:
  push:
    paths:
      - bootloader/**
permissions:
  contents: write
jobs:
  build-bootloader:
    name: Build bootloader
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3
      - name: Determine short GIT hash
        id: short-sha
        run: |
          echo "sha=$(echo ${{github.sha}} | sed 's/^\(.\{10\}\).*$/\1/')" >> $GITHUB_OUTPUT
      - name: Build bootloader
        uses: ryanwinter/arm-none-eabi-gcc@master
        with:
          release: '10.3-2021.10' # The arm-none-eabi-gcc release to use.
      - run: |
          cd bootloader
          make
          cp -f bootloader-dfu-fw.bin ../docs/
      - name: "[Automated] Upload bootloader to project website"
        uses: EndBug/add-and-commit@v9 # You can change this to use a specific version.
        with:
          add: 'docs/bootloader-dfu-fw.bin'
          author_name: Michael Fitzmayer
          author_email: mail@michael-fitzmayer.de
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          path: docs/bootloader-dfu-fw.bin
