name: Firmware
on:
  push:
    paths:
      - firmware/**
jobs:
  build-firmware:
    name: Build firmware
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3.1.0
      - name: Determine short GIT hash
        id: short-sha
        run: |
          echo "sha=$(echo ${{github.sha}} | sed 's/^\(.\{10\}\).*$/\1/')" >> $GITHUB_OUTPUT
      - name: Build firmware
        uses: xanderhendriks/action-build-stm32cubeide@v10.0
        with:
          project-path: 'firmware'
          project-target: 'TrackMAG'
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Patch firmware header
        run: |
          mkdir export
          cp firmware/Release/TrackMAG.bin export/
          python bootloader/checksum.py export/TrackMAG.bin
