name: firmware
on:
  push:
    paths:
      - firmware/**
permissions:
  contents: write
jobs:
  build-firmware:
    name: Build firmware
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3
      - name: Determine short GIT hash
        id: short-sha
        run: |
          echo "sha=$(echo ${{github.sha}} | sed 's/^\(.\{10\}\).*$/\1/')" >> $GITHUB_OUTPUT
      - name: Build firmware
        uses: xanderhendriks/action-build-stm32cubeide@v10.0
        with:
          project-path: 'firmware'
          project-target: 'TrackMAG'
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.8
      - name: Patch firmware header
        run: |
          cp -f firmware/Release/TrackMAG.bin docs/TrackMAG-latest.bin
          python bootloader/checksum.py docs/TrackMAG-latest.bin
      - name: "[Automated] Upload firmware to project website"
        uses: EndBug/add-and-commit@v9 # You can change this to use a specific version.
        with:
          add: 'docs/TrackMAG-latest.bin'
          author_name: Michael Fitzmayer
          author_email: mail@michael-fitzmayer.de
          message: 'Upload firmware binary to project website'
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          path: binaries/TrackMAG-latest.bin
